### ISSUE TITLE
No such method 'for' for invocant of type 'Array'

### ISSUE THREAD

**Issue by bbkr** [moritz/json#14]
Rakudo moar 2015.03 installed using rakudobrew.
JSON::Tiny f889af3c6e67ab645eca0795afff8d9d247ca54a (HEAD at the moment of submitting this issue).

```
$ panda install JSON::Tiny
==> Fetching JSON::Tiny
==> Building JSON::Tiny
Compiling lib/JSON/Tiny/Actions.pm to mbc
Compiling lib/JSON/Tiny/Grammar.pm to mbc
Compiling lib/JSON/Tiny.pm to mbc
==> Testing JSON::Tiny
t/01-parse.t ...... ok
t/02-structure.t .. ok
t/03-unicode.t .... ok
t/04-roundtrip.t .. No such method 'for' for invocant of type 'Array'
  in sub to-json at lib/JSON/Tiny.pm:37
  in block  at t/04-roundtrip.t:37

t/04-roundtrip.t .. Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 17/17 subtests
```

**Comment by moritz** [comment]
This is very puzzling. Are you sure you actually used the right rakudo? json is part of rakudo star, and passed all tests there; the only new commit since 2015.03 changed META.info.

**Comment by bbkr** [comment]
```
This is perl6 version 2015.03 built on MoarVM version 2015.03
```

I can reproduce bug only when installing through Panda provided by rakudobrew.
Checking on another machine right now...

**Comment by bbkr** [comment]
I've checked install log and rakudobrew failed to install panda dependency Shell::Command and used some old version. Rebootstrapping panda solved the issue with JSON::Tiny installation.
