### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by czipperz** [moritz/json#17]
When I try to make or make install, it gives the following error:

    ===SORRY!=== Error while compiling lib/JSON/Tiny/Actions.pm
    Undeclared routine:
        unit used at line 1. Did you mean 'uniq'?

    Makefile:22: recipe for target 'blib/lib/JSON/Tiny/Actions.pm.moarvm' failed
    make: *** [blib/lib/JSON/Tiny/Actions.pm.moarvm] Error 1

**Comment by moritz** [comment]
This means that your rakudo is too old. If you want to continue to use your old rakudo, please use the JSON::Tiny from the corresponding Rakudo Star release; otherwise please update your rakudo installation to 2015.05 or newer.

**Comment by czipperz** [comment]
The distribution I use (from the AUR) is at 2015.03 and the version on rakudo.org where they outline how to build from source is 2015.02. How do I go about getting this new copy?

**Comment by moritz** [comment]
see http://rakudo.org/how-to-get-rakudo/
