### ISSUE TITLE
Roundtrip test failure on rakudo-latest

### ISSUE THREAD

**Issue by drforr** [moritz/json#18]
This is perl6 version 2015.07.1-83-g035a75b built on MoarVM version 2015.07-8-gb8fdeae

> Failed test 'Array of Stuff'
> at t/04-roundtrip.t line 39
> expected: [{"A hash" => 1}, ["an", "array", "again"], 2]
>      got: [{"A hash" => 1}, "an", "array", "again", 2]
> Looks like you failed 1 test of 17
> t/04-roundtrip.t .. 
> Dubious, test returned 1 (wstat 256, 0x100)
> Failed 1/17 subtests

**Comment by moritz** [comment]
Seems to work again with current Rakudo; can you confirm that?

**Comment by zoffixznet** [comment]
Passes me when installing with panda:

```bash
==> Fetching JSON::Tiny
==> Building JSON::Tiny
==> Testing JSON::Tiny
t/01-parse.t ...... ok
t/02-structure.t .. ok
t/03-unicode.t .... ok
t/04-roundtrip.t .. ok
t/05-utf16.t ...... ok
All tests successful.
Files=5, Tests=122, 17 wallclock secs ( 0.09 usr  0.00 sys + 16.30 cusr  0.47 csys = 16.86 CPU)
Result: PASS
==> Installing JSON::Tiny
Copying blib/lib/JSON/Tiny.pm to /home/zoffix/.rakudobrew/moar-nom/install/share/perl6/site/lib/JSON/Tiny.pm
Copying blib/lib/JSON/Tiny/Actions.pm to /home/zoffix/.rakudobrew/moar-nom/install/share/perl6/site/lib/JSON/Tiny/Actions.pm
Copying blib/lib/JSON/Tiny/Grammar.pm to /home/zoffix/.rakudobrew/moar-nom/install/share/perl6/site/lib/JSON/Tiny/Grammar.pm
==> Successfully installed JSON::Tiny
```

**Comment by moritz** [comment]
I can't reproduce it either.
