### ISSUE TITLE
Unable to iterate over an array

### ISSUE THREAD

**Issue by GildedHonour** [moritz/json#21]
I make an http request and a server returns a json data which consists of an array. However, I cannot iterate over it because "for" treats it as a single element. But I can access its values by index, nonetheless.

The json data has the following structure:
```
{"ok":true,
  "res":[
    {"var1":342343, "var2":{"var3":...
    {"var1":222, "var2":{"var3":...
    {"var1":3334343999, "var2":{"var3":...
  ]
}
```
So it consists of an array for sure.

And the code:
```
my @my-json = from-json($resp.content){"res"};



# for @my-json[0] -> @k { # the same -- only 1 iteration with 3 values accessible by index

for @my-json -> @k {
  say "iteration"                             # only 1 iteration
  say "1: {@k[0]{'var1'}}";    # ok
  say "2: {@k[1]{'var1'}}";   # ok
  say "3: {@k[2]{'var1'}}";   # ok

}
```

I've tried "map" -- the result way the same, obviously -- only one iteration.

**Comment by b2gills** [comment]
You want one of the following

    my @json = @(from-json($resp.content)<res>);
    my @json := from-json($resp.content)<res>;
    my @json = from-json($resp.content)<res>[];
    my @json = |from-json($resp.content)<res>;
    my $json = from-json($resp.content)<res>;

What you have puts the array from the JSON structure as the first element of your array.
(Your problem has nothing to do with this module)

**Comment by moritz** [comment]
Or my favorite solution:

   my @json = from-json($resp.content)<res>.list;

(if you prefer method calls over punctuation)

**Comment by GildedHonour** [comment]
Thanks. How is this  "@(from-json($resp.content)<res>);" or this "from-json($resp.content)<res>.list" operation called -- casting to an array?
