### ISSUE TITLE
Fails to parse JSON that other parsers accept

### ISSUE THREAD

**Issue by moritz** [moritz/json#25]
Input:

    ["̥̞ͫͩ̉̎͊ỏ̟͙̞̻̻̹̹r̵̨͇̫̦̺̮̼ͭ,̷̧̬̲͈̤̤̅̉͛ͫ͠ ̣͕̝̳̗̲̩̣͗̋͘e̼ͩ̔̿̾̋̾͘a̸̙͙͔̜͙̳̻͊ͯͪͤͬ͊͆͠c̦̃̓̈̾͗́͝͝ḩ͉͓̦̯̞̆ ̵͇͍ͪ̀́w̷ͩ͗̃͒͏̲̼̯̕i̞̫̜̮̣̰͎̅̂͋̀ͅń̢̨̪̭̠̼͕͎̐́͆̅ͅd̰̤̝͎̹͕ͩ̃̏̃̍͊̔ȏ̶̼̺̪̾ͨ̈̄ͤ̄̚̕w̙̻̱̙̺͎͚̙ͧͪ̊̒̕͝ ̴̼̰̱͈̠ͤ̋̏̇͛&̠̺̟̞͎̳̻̙̽̓́̔̇ͩ͛ͧ̚ ̡̡̫̻͐̌̐̌ͬͦ̂͞"]

Other JSON-Modules (like p5 ones) accept this.

**Comment by AlexDaniel** [comment]
Another similar case is:
```
"‍"
```
(ZERO WIDTH JOINER between the quotes)

**Comment by moritz** [comment]
The problem here is that if a combining character of some sorts follows the double quote, the quote and the combining character get combined into a single grapheme, so `<that character> ~~ / '"' /` doesn't match.

A possible workaround might be to match with `:ignoremark`, but then the combiner is lost. So maybe we have to capture the matched left quote, see if it has any combiners, and if yes, move it to the string.

That's a bit ugly, but probably the only solution that works without Rakudo and/or Perl 6 changes.
