### ISSUE TITLE
Allow extra commas at end of lists

### ISSUE THREAD

**Issue by hakonhagland** [moritz/json#35]
I have some JSON configuration files that I use for setting up stuff on my computer. 
I have written a parser in Perl 5 using [`JSON::XS`](https://metacpan.org/pod/JSON::XS) and I am setting the `relaxed` flag in that module to allow extra commas at end of lists (similar to Perl syntax which also allow extra commas at end of lists). This is very convenient for me when editing these configuration files.

Now I am starting to translate the framework to Perl 6, but `JSON::Tiny` does not have a `relaxed` flag currently, and I am not able to parse my configuration files in Perl 6. I looked into the source code of `JSON::Tiny::Grammar` and it seems we only need to change `%` to `%%` in the `pairlist` and `arraylist` rules of the grammar to enable relaxed parsing.

Would you consider including such an option, or do you think it would break with the "simplicity" of the module as it is now? Thanks for the nice work!

**Comment by moritz** [comment]
As long as ACME-404 and RFC 7159 (or RFC 8259, which seems to supersede RFC 7159) don't allow trailing commas, I'm loath to add that to JSON::Tiny. I think [JSON::Fast](https://github.com/timo/json_fast) might be more open to this kind of feature request.

**Comment by jnthn** [comment]
Just a note to say that making a `JSON::Relaxed` module based upon `JSON::Tiny` would mostly be a matter of subclassing its grammar and overriding the rule that parses arrays.

**Comment by hakonhagland** [comment]
@moritz Yes I agree with your decision. There is the problem by introducing new features that is slightly outside the scope of the module. @jnthn Thanks for the comment! I did not think about that option. I think that is a great solution to my problem.
