### ISSUE TITLE
version mismatch (and pls add git tags!)

### ISSUE THREAD

**Issue by AntonOks** [moritz/json#43]
WARNING: Version mismatch for JSON-Tiny ("https://github.com/moritz/json.git") found. META6.json has "1.0" but latest 'git tag' is "version-0.1.0"

Can you please add the git tag "v1.0", pointing to the same commit you declared this version in META6?
See also #41

**Comment by AntonOks** [comment]
@moritz ping

**Comment by moritz** [comment]
I have pushed a tag `v1.0`
